name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Deloyment task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun install --frozen-lockfile
          bun publish
